Лабораторная работа 2
AlekseyF3/kabspythonkorneenkov pull request #2
Opened 2024-10-22 11:28 UTC by AlekseyF3

2024-10-29 17:41 UTC, rmushkin requested changes
Кроме округления всё правильно, пожалуйста, поправьте

2024-10-29 17:41 UTC, rmushkin commented on Лабораторная работа 2/task2.py
> +for i in range(1, months):
(не ошибка) питоничнее использовать _ вместо имени переменной. Это полностью валидное имя, т. к. нижнее подчёркивание считается обычной буквой; однако выглядит как "пустое место" и дополнительно самодокументирует код, указывая на неиспользуемость значения.

2024-10-29 17:41 UTC, rmushkin commented on Лабораторная работа 2/task2.py
> +print(f"Подушка безопасности, чтобы протянуть {months} месяцев без долгов:", round(money_capital))
Ловушка с `round`: 3 рублей не хватит, чтобы купить гвоздь за 3 рубля 25 копеек. Надо округлять в большую сторону.

2024-10-31 12:23 UTC, rmushkin requested changes
Поясните, пожалуйста, насчёт %10. И заодно исправьте скобки.

2024-10-31 12:23 UTC, rmushkin commented on Лабораторная работа 2/task2.py
> +        money_capital = int(money_capital) + 1
+1 за решение собственными силами!
Но позвольте, почему %10?

2024-10-31 12:23 UTC, rmushkin commented on Лабораторная работа 2/task2.py
> +print(f"Подушка безопасности, чтобы протянуть {months} месяцев без долгов:", (money_capital))
круглые скобки вокруг `money_capital` совершенно излишни

2024-10-31 13:13 UTC, AlekseyF3 commented on Лабораторная работа 2/task2.py
> +        money_capital = int(money_capital) + 1
Извините, поторопился. и даже не проверил, что пишу, так оно не работало для большого количества чисел (для всех, которые не оканчивались на 0), подправил. Хотя ответ удивительным образом всё равно получился тот же... %10, потому что если остаток от деления на 10 будет 0, значит число будет целым (при условии, что оно будет предварительно ещё домножено на 10, потому что условно для числа 55 такая схема не сработает, а вот для 550...). А если число оказывается дробным, то каким бы оно не было, остаток от деления на 10 всё равно будет не 0, и тогда его можно округлить в большую сторону, предварительно откинув числа после запятой с помощью int и добавив единицу

2024-10-31 14:34 UTC, rmushkin approved these changes
Принимается ✅ 
Впрочем, не могу не заметить, что 10 справа и слева вполне можно сократить 😁 
В плане того, что в пайтоне `100500.55 % 1 = 0.55`.

2024-10-31 14:35 UTC, merged