Лабораторная работа 3
AlekseyF3/kabspythonkorneenkov pull request #3
Opened 2024-10-22 19:50 UTC by AlekseyF3

2024-11-07 19:58 UTC, rmushkin requested changes
Мало что можно сказать - увы, вы не запускали собственный код. По крайней мере, тот, который загрузили сюда.

2024-11-07 19:58 UTC, rmushkin commented on Лабораторная работа 3/task1.py
PEP8

2024-11-07 19:58 UTC, rmushkin commented on Лабораторная работа 3/task2.py
> +    second = "Петров|Сидоров|Смирнов"
Что это??!?!!

2024-11-07 19:58 UTC, rmushkin commented on Лабораторная работа 3/task2.py
> +def find_common_participants(first, second, znak=","):
PEP8

2024-11-07 19:58 UTC, rmushkin commented on Лабораторная работа 3/task3.py
Код не запускается. Проверять не буду, пока вы сами не сделаете так, чтобы он запускался.

2024-11-07 20:27 UTC, AlekseyF3 commented on Лабораторная работа 3/task2.py
> +    second = "Петров|Сидоров|Смирнов"
Честно говоря, не помню, зачем туда эти строчки вообще поставил, видимо наваждение...

2024-11-07 20:28 UTC, AlekseyF3 commented on Лабораторная работа 3/task3.py
Эту версию действительно не запускал, извините. Исправлял пару дней назад в спешке с телефона, чтобы переменная называлась нормально, и в одном месте всё-таки упустил

2024-11-08 10:44 UTC, rmushkin requested changes
Спасибо, теперь запускается. Осталось одно мелкое замечание.

2024-11-08 10:44 UTC, rmushkin commented on Лабораторная работа 3/task3.py
> Исправлял пару дней назад в спешке с телефона

Это прямо уровень сисадмина из анекдота начала нулевых... Который из отпуска с кнопочного телефона смсками правил продакшен... 😅

2024-11-08 10:44 UTC, rmushkin commented on Лабораторная работа 3/task3.py
> +    frequency = {key: round(value / letters, 2) for key, value in letter_count.items()}
Теперь переходим к настоящим замечаниям. Вот тут - преждевременное округление. Физический смысл (ещё говорят "бизнес-логика") ничего не говорит об округлении частоты (в отличие, например, от денег из прошлой лабораторной). Поэтому тут округлние - исключительно фишка вывода на экран.

2024-11-08 10:44 UTC, rmushkin commented on Лабораторная работа 3/task3.py
> +    print(f"{key}: {value: .2f}")
Вот же, тут есть округление. Всё, этого достаточно...

2024-11-08 11:00 UTC, rmushkin approved these changes
Принимается ✅

2024-11-08 11:00 UTC, merged